### ISSUE TITLE
Maude 3.5beta (precompiled): GLIBC_2.36 requirement

### ISSUE THREAD

**Issue by haijinSk** [SRI-CSL/Maude#17]
I apologize; this is more an implicit rhetorical question than bug reporting.

With Maude 3.5beta (the binary from Maude-linux.zip) I got this:

```
$ maude.linux64 
maude.linux64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by maude.linux64)

```
Yes, my OS does not have the exact version of the library: 

```
$ ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3.8) 2.35
```

I'm not a Linux power user (I'm happy if I can ignore OS details in context of programming languages), so I'm somewhat reluctant/afraid of upgrading something on my own if I feel that it's maybe important for the whole system I don't know much about.

I don't know if this requirement is intended, so to speak... If it is, it's ok; It's up to me the things/configuration of my OS and I'm only experimenting with/learning Maude out of my personal curiosity (like: the magic of rewriting...).

Anyway, thank you.

**Comment by haijinSk** [comment]
After reading this: https://github.com/maude-lang/Maude/issues/3

I think, it seems to me, it's matter of fact the requirement; like time and versions of everything are going forward...

**Comment by haijinSk** [comment]
After reading this: https://github.com/maude-lang/Maude/issues/3

I think, it seems to me, it's matter of fact, the requirement; like time and versions of everything are going forward...

**Comment by haijinSk** [comment]
After reading this: https://github.com/maude-lang/Maude/issues/3

I think, it seems to me, it's matter of fact, the requirement; time and versions are going forward...

**Comment by stevenmeker** [comment]
The required glibc library depends on the machine the binary is built on. Previous Linux binaries were built on a machine at SRI that hadn’t been updated in years and had older libraries. The current binary was built on my personal machine which is up to date. You should be able to build from source using the instructions in INSTALL on any version of Linux released in the last 5 years or so.

**Comment by haijinSk** [comment]
Thank you very much for the response/answer...
