### ISSUE TITLE
Fail to run Maude 3.2.1 on Ubuntu 18.04

### ISSUE THREAD

**Issue by rgyen** [SRI-CSL/Maude#3]
Hi, I downloaded Maude release version 3.2.1 (from [here](https://github.com/SRI-CSL/Maude/releases/tag/3.2.1)) and tried to run it on my Ubuntu 18.04. 

I got the following error message:

> $./maude.linux64
> ./maude.linux64: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./maude.linux64)

I checked my GLIBC version GLIBC with ldd:

> $ldd --version
> ldd (Ubuntu GLIBC 2.27-3ubuntu1.5) 2.27

I use Ubuntu's default compiler.
I think I need to upgrade my glibc manually (by building it from source) in order to use Maude 3.2.1.

Is there any other way to resolve this issue (other than manual building)?

**Comment by lkyskr** [comment]
I started Maude without any problems after installing Glibc 2.29

**Comment by stevenmeker** [comment]
The pre-built Linux binary for Maude 3.3 depends on glibc 2.27 so it should work on older systems.

**Comment by rgyen** [comment]
> The pre-built Linux binary for Maude 3.3 depends on glibc 2.27 so it should work on older systems.

Thanks!
