### ISSUE TITLE
Issue with non-constant SIGSTKSZ

### ISSUE THREAD

**Issue by mjsottile** [SRI-CSL/Maude#4]
It appears that SIGSTKSZ is no longer constant on some systems (see : https://sourceware.org/git/?p=glibc.git;a=blob;f=NEWS;h=85e84fe53699fe9e392edffa993612ce08b2954a;hb=HEAD).  This causes a build failure in src/Mixfix/interact.cc:

```
In file included from ../../../src/Mixfix/userLevelRewritingContext.cc:75:
../../../src/Mixfix/interact.cc: In static member function ‘static void UserLevelRewritingContext::setHandlers(bool)’:
../../../src/Mixfix/interact.cc:120:15: error: storage size of ‘altStack’ isn’t constant
  120 |   static char altStack[SIGSTKSZ];
```

A potential fix can be found here in another project that had a similar problem : https://github.com/geomechanics/mpm/issues/61#issuecomment-1180758920

I encountered this problem building from source on an Ubuntu 22.04 system.

**Comment by stevenmeker** [comment]
This is fixed in Maude 3.2.2.
