### ISSUE TITLE
Notes for building from source on macOS

### ISSUE THREAD

**Issue by rljacobson** [SRI-CSL/Maude#5]
There is not much in the way of build instructions. I took some notes during my attempt at building Maude on macOS 12.6. I thought they might be useful to other people. Would you be interested in including something similar to this in the Maude repository?

# Building on macOS

A couple of old brew files exist for installing old versions of Maude with Homebrew. There does not seem to be a guide anywhere on compiling Maude from source.

### Dependencies required:

 - [BuDDy](https://sourceforge.net/p/buddy/gitcode/ci/master/tree/): Binary Decision Diagrams. Version requirements unknown. I configured it following [Iván Martínez Mateu's brew file](https://github.com/iMartinezMateu/homebrew-maude/blob/master/libbuddy.rb)
 - [GNU libsigsegv](https://www.gnu.org/software/libsigsegv/): a library for handling page faults in user mode. Available from Homebrew: `brew install libsigsegv`.
 - [Tecla](https://sites.astro.caltech.edu/~mcs/tecla/index.html): interactive command line editing facilities. Available from Homebrew: `brew install libtecla`.
 - [Yices](https://yices.csl.sri.com/): SMT solver. Available on GitHub and from Homebrew: `brew install SRI-CSL/sri-csl/yices2`. Alternatively, you can use CVC4.
 - [CVC4](https://cvc4.github.io/): SMT solver. Available on GitHub and from Homebrew: `brew tap cvc4/cvc4` and then `brew install cvc4/cvc4/cvc4`. Since CVC4 has been superseded by cvc5, I chose Yike2. I don't know if Yikes2 is better or not. YMMV.
 - [GMP](https://gmplib.org/): The GNU Multiple Precision Arithmetic Library. Homebrew: `brew install gmp`.

### Compilation Dependencies

Dependencies of the build system rather than of the project code itself. This list is not exhaustive.

 - autotools
 - flex
 - bison: Minimum version unknown, but you need a newer version than macOS provides. I used bison 3.8.2. Availabe from Homebrew: `brew install bison`. However, Homebrew will not shadow the system bison. You must make sure the newer version of bison is first in your $PATH.

## Build instructions

Maude appears to use the "standard" autotools build system, which is ancient by today's standards, but if it ain't broke... The configure script is not included in the sources, but it can be generated from `configure.ac`, which is included. To generate it, run:

```bash
$ autoreconf --install
```

Then run configure:

```bash
$ ./configure
```

Then make. Use the flag `-jN`, replacing `N` with the number of cores your computer has. This is likely to significantly reduce the build time.

```bash
$ make -j4
```

If the build fails with an error about a header file not being found, it is likely due to one of the dependencies above being missing. Install the dependency, then run `make` again. The build will pick up where it left off.

**Comment by stevenmeker** [comment]
The INSTALL file now has detailed instructions from building from source for both Linux and Mac.

**Comment by rljacobson** [comment]
@stevenmeker On Apple Silicon, libbuddy fails to build. This issue is actually with an outdated config tool. If you replace `tools/config.guess` and `tools/config.sub` in the libbuddy source tree with [the most recent versions](https://git.savannah.gnu.org/gitweb/?p=config.git;a=tree;h=63acb96f92473ceb5e21d873d7c0aee266b3d6d3;hb=63acb96f92473ceb5e21d873d7c0aee266b3d6d3), everything is fine.

Obviously this isn't an issue with Maude, but there doesn't seem to be an explanation anywhere else on the internet of this problem and solution. That might just be a reflection of my google fu, though.
